### ISSUE TITLE
nvml_setup.sh does not work, needs a little more information for beginners

### ISSUE THREAD

**Issue by baconsmokeco** [SveSop/nvidia-libs#15]
There's not a lot of info about how to run the nvml_setup.sh command. When I try to run it I get the following error:
    WINE_BIN is not set!
    Example: WINE_BIN='/home/user/winebinaries/wine-staging/'
    OBS. Installing to system wine install is not recommended.
    Better use custom wine binary.

However, there's nothing to explain how to do this. I tried setting WINE_BIN=/opt/wine-staging/ in hopes that was what it wanted. It did not help. So, I suspect I'm missing something fairly obvious, but after a lot of searching on the internet, I have not found anything that helps explain what it needs or how to define this. Perhaps some documentation to explain what prereqs are required to overcome the error message it gives? Thank you.

**Comment by baconsmokeco** [comment]
Well, after imitating the instructions you have for setup_nvlibs.sh it worked. I.e.
sudo WINE_BIN=/opt/wine-staging/ nvml_setup.sh

So, you can either ignore this or for additional morons like myself, put the full command needed to get this to work in the install section on the main page.

**Comment by SveSop** [comment]
The example is mostly "generic", cos usually i tend to NOT tamper with package installed binaries like those in `/opt/wine-staging` (need to use SUDO for one thing).

Those that do not use a custom-compiled version that they compile themselves or download from GloriousEggroll, TKG or similar can easily enough just copy the /opt/wine-staging binaries to a folder in your own userfolder, so any tampering will NOT f** up your distro installed wine nor require SUDO command.

AND whenever upstream distro wine gets updated you do not have to rely on downgrading packages in case of breakage.

Gonna close this, but will give you a couple of hints:

Lets say your user is baconsmokeco and you are in your home folder /home/baconsmokeco/

mkdir wine
cd wine
cp -r /opt/wine-staging wine-staging-9.0

Then you will have a copy of wine-staging-9.0 that you can mess around with (depending of what wine version is installed ofc)

WINE_BIN=/home/baconsmokeco/wine/wine-staging-9.0 ./nvml_setup.sh

Whenever you run wine you make a script using:
PATH=/home/baconsmokeco/wine/wine-staging-9.0/bin:$PATH

This will make you use THAT particular wine version. I will also recommend (as most wine users do) that you use separate wineprefixes for every program you run, that way any overrides or winetricks adds will not mess up other programs

eg. WINEPREFIX=/home/baconsmokeco/wine/SOMEAPP

Benefit: You dont need SUDO, and you will not mess up the distro installed packages + you do not need to redo everything if distro upgrades packages
Drawback: You have to copy distro package folder and update script every time you want to switch to a new version of wine. (Small price to pay imo)

Example of script you can build on to run an app:

```
PATH=/home/baconsmokeco/wine/wine-staging-9.0/bin:$PATH
export WINEPREFIX="$HOME/Wine/SOMEAPP"
export WINEDEBUG="-all"
export VKD3D_DEBUG=none
export VKD3D_SHADER_DEBUG=none
export VKD3D_CONFIG=dxr11
export DXVK_LOG_LEVEL=none
export DXVK_ENABLE_NVAPI=1
cd "$WINEPREFIX/drive_c/Program Files/SOMEAPP/" || exit
wine ./someapp.exe
```
Customize this by replacing whatever folder you need for your prefix and actual installed app/program and so on and so forth. (You would need DXVK for nvapi usage, but VKD3D is not mandatory).

Hopefully some helpful tips 😄
