### ISSUE TITLE
request: bottles -flatpak support

### ISSUE THREAD

**Issue by kurageart** [SveSop/nvidia-libs#17]
Hello, and thank You for your project.. This adds to wine a great usability boost , since most of the new projects are mostly focusing on gaming only. I'd like to know if is possible installing one of the release versions in a bottle , choosing an appropriate runtime, simply copying or linking the files to the bottle directory. If yes, where? I tried to copy the symlinks to windows/system32 , but I guess that it would be necessary some other sort of override, since cuda is not working there.
No problems at all installing the latest release in a "real" winehq stable version in debian , but I could like avoiding multiarchitecture and all the various dependencies, if possible..

**Comment by kurageart** [comment]
Thank You so much.. I was trying to sort out this issue here https://github.com/bottlesdevs/Bottles/issues/3301 with the user Obreo .  I copied the files from the respective architectures directly to the runner folder , and then did the overrides in wincfg ..It seems it worked for him, not for me unfortunately

**Comment by SveSop** [comment]
It is no huge problem getting this to work for cuda. I suppose one could figure out a way to replace nvapi files if it would be needed for some unreal engine demo's or something that sometimes uses those extra nvapi calls i got in my custom version.

But for cuda and/or physx usage in bottles you do the following:

Copy the `nvidia-libs/lib64/wine/x86_64-unix/nvcuda.dll.so` to your "bottle's" windows/system32 folder as nvcuda.dll overwriting whetever that may exist there.
eg. `cp nvidia-libs/lib64/wine/x86_64-unix/nvcuda.dll.so .var/app/com.usebottles.bottles/data/bottles/bottles/Test/drive_c/windows/system32/nvcuda.dll`
(My "bottles" is then called "Test")

Then you make a DLL override in your bottle GUI overriding `nvcuda`

This did NOT seem to work if i used a symlink, as i suppose it may not be possible for the bottle to run symlinks "outside" of the bottle so to speak? If i copied the file it worked just fine.. but you must copy the .dll.so file as .dll basically renaming it.

This would probably work if you copy nvapi.dll files aswell, but i guess would be replaced if you toggle or change settings.

**Comment by kurageart** [comment]
Lovely! It works perfectly! I'll spread the word on Bottles github page!

**Comment by SveSop** [comment]
Setting this to solved then, as it works if you do it manually, and it is kind of up to the bottles devs if they want to implement nvcuda as a own feature 😄
