### ISSUE TITLE
failed to compile on ubuntu 24.04

### ISSUE THREAD

**Issue by kipodon** [SveSop/nvidia-libs#19]
I tried to build this on ununtu 24.04
I installed all dependencies from ubuntu repository.
and I get this error in masson-log.txt

Running command: winegcc -b x86_64-w64-mingw32 -E -dM -

meson.build:1:0: ERROR: Unable to detect GNU compiler type:
Compiler stdout:

-----
Compiler stderr:
winegcc: Could not find g++

and of course I have g++ installed.

**Comment by SveSop** [comment]
I tend to use Arch for building, so i have not really tested this much on Ubuntu, let alone 24.04.

Do you have the mingw-w64 packages installed? dxvk-nvapi and wine-nvml uses mingw-w64 to build the PE part of the library, and the command `winegcc -b x86_64-w64-mingw32 -E -dM -` is from the wine-nvml part of the build.

Would require typically this for Ubuntu:
`apt install build-essential mingw-w64 gcc-12 g++-12 g++-12-multilib gcc-12-multilib`

You could also try to build wine-nvml standalone just to see if builds: https://github.com/Saancreed/wine-nvml

**Comment by kipodon** [comment]
Hi,
thanks for you help.
I had only gcc-mingw-w64 and not all mingw-w64 packages.
so I could compile with gcc 13 ( the default for ubuntu 24.04)
I have 2 suggestions for this project:
1. allow to compile only 64 bit libraries. 32 bit in both windows and linux are not widely used. and this will simply build. 
2. setup_nvlibs.sh uses wine64. wine64 may not be in the path. it might be a good idea to add a warning in the script if wine64 fail to execute.

**Comment by SveSop** [comment]
1. There are a few loaders/launchers that still are 32-bit even if the game itself is 64-bit, and the benefit of the little compile-time saved on generating only 64-bit is not that huge an issue. I am a wee bit unsure atm if any 32-bit -dev or lib packages is required to build 32-bit version, but possibly that can turn out to be the case in the future.
2. Is it the case for Ubuntu 24.04 that there is no 32-bit wine available? As it is now, the script is not really meant to be used with a "pure 64-bit wine" setup (As in building custom wine for only 64-bit). I may look into that perhaps...
