### ISSUE TITLE
Building nvidia-libs fails on wine 9.10 with "cannot find -lwinecrt0: No such file or directory" 

### ISSUE THREAD

**Issue by schloegl** [SveSop/nvidia-libs#20]
I'm trying to set up nvidia_libs for wine 9.10 but it fails with this error

```
[3/4] Linking target src/nvml.dll
FAILED: src/nvml.dll 
winegcc -b x86_64-w64-mingw32.static  -o src/nvml.dll src/nvml.res src/nvml.dll.p/nvml.c.obj -Wl,--allow-shlib-undefined -Wl,-O1 -shared -Wl,--start-group -Wl,--out-implib=src/nvml.dll.a -mno-cygwin -Wl,--wine-builtin /nfs/scistore16/itgrp/schloegl/src/nvidia-libs/wine-nvml/src/nvml.spec -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 -Wl,--end-group
/nfs/scistore07/clustersw/shared/mxe/usr/bin/x86_64-w64-mingw32.static-ld: cannot find -lwinecrt0: No such file or directory
collect2: error: ld returned 1 exit status
winegcc: /mnt/nfs/clustersw/shared/mxe/usr/x86_64-pc-linux-gnu/bin/x86_64-w64-mingw32.static-gcc failed
ninja: build stopped: subcommand failed.

```

I'm using the latest commit 220a160c0a3807adfa662edd013d1e84914eb390, and test this with cuda/12.0.0 and cuda/12.2.0 

Installing the same version of nvidia-libs on wine/9.9 works fine.

**Comment by SveSop** [comment]
Probably some header changes with wine-10 that causes this. Will look into it

**Comment by SveSop** [comment]
I see you refer to "installing", but building the package is not "installing".. it is "building". Just so we agree on terms here.

I built nvidia-libs with that commit both on Arch with wine-10 and on Ubuntu 22.04 using wine-staging-9.10 (WineHQ packages).

If running Ubuntu with WineHQ packages, check that you have:
```
/opt/wine-staging/lib/wine/i386-unix/libwinecrt0.a
/opt/wine-staging/lib/wine/i386-windows/libwinecrt0.a
/opt/wine-staging/lib64/wine/x86_64-unix/libwinecrt0.a
/opt/wine-staging/lib64/wine/x86_64-windows/libwinecrt0.a
```

PS. Without really knowing about the multitude of build-systems out there, it may seem as a MinGW problem perhaps?
`/nfs/scistore07/clustersw/shared/mxe/usr/bin/x86_64-w64-mingw32.static-ld: cannot find -lwinecrt0: No such file or directory`

Now sure what `x86_64-w64-mingw32.static` means in this context... Some MinGW variant you use on your buildsystem that might not have libwinecrt?

**Comment by schloegl** [comment]
It seems my wine installation is broken - sorry for the noise .
