### ISSUE TITLE
Please help me to get the Supersonic Sled demo running on Linux

### ISSUE THREAD

**Issue by Noobyuser** [SveSop/nvidia-libs#22]
Hello,

first of all please excuse me, because I am not very skilled!

So I got the Supersonic Sled demo installed into a fresh 64-bit WINEPREFIX via WINE-Staging 9.12 on Ubuntu 22.04 LTS, including the latest DXVK 2.3.1.

Plus I installed your nVidia-libs collection into the same prefix and made sure that all tests passed successfully with the included test program.

And I had installed PhysX itself into the same prefix with this command:

`winetricks --force -q physx`

Additionally, also these ones:

`winetricks directshow wmp11`

Finally, I added a dxvk.conf file with the necessary content to unhide my nVidia 1650 Turing GPU.

When I tried to actually run the demo, it did boot up and show the initial splash-screen that it's getting ready for take-off!

Unfortunately, it never does, preferring to crash instead...

Now just recently I saw in the README that I need to somehow extract the old 32-bit libraries of CUDART 3.0 and link them in order to get this old demo running.

However, I have no clue how to do that!

Could you please hint me in the right direction or even provide the right commands to copy & paste into a terminal?

I would be forever grateful!

Thanks a ton for the awesome work that you do!!

**Comment by SveSop** [comment]
First of all, i seemed to need more ref. https://github.com/SveSop/nvidia-libs/issues/18#issuecomment-2012695123

`winetricks physx d3dx11_43 d3dcompiler_43 lavfilters directshow wmp11`

Easiest way to get this demo to run is to download an older nvidia-libs that do not need this, as it will work just as fine for this demo. So if you download the 0.7.16 release (from https://github.com/SveSop/nvidia-libs/releases), and use that instead + the winetricks verbs i mention above, it should run in a much easier manner than this CUDART relay hack i created.

If you do want to try the CUDART trick you need to do the following - I only tested this with Ubuntu 22.04, so i am not sure if it works with Arch or Gentoo or some non-debian derivative:

Download the `cudatoolkit_3.0_linux_32_ubuntu9.04.run`  file and make it executable with `chmod a+x cudatoolkit_3.0_linux_32_ubuntu9.04.run`.
Then you extract the files in a subfolder of your choosing like this: `./cudatoolkit_3.0_linux_32_ubuntu9.04.run --target toolkit --noexec` (This will extract the files in the "toolkit" subfolder).

Next you enter the folder where the supersonic sled demo is installed in your wineprefix - eg. `/home/username/wine/SuperSonicPrefix/drive_c/Program Files (x86)/NVIDIA Corporation/NVIDIA Demos/Supersonic Sled/bin/`
Here you rename `cudart32_30_11.dll` to something like `cudart32_30_11.dll_BACKUP`
Then you create a symlink to the included "relay" version in nvidia-libs like this (to the folder where nvidia-libs is extracted):
`ln -sf /home/username/nvidia-libs/lib/wine/i386-unix/cudart32_30_14.dll.so cudart32_30_14.dll`

Then you export LD_LIBRARY_PATH like this (To the folder where you extracted the cudatoolkit files previously):
`export LD_LIBRARY_PATH=/home/username/toolkit/lib:$LD_LIBRARY_PATH`

Then proceed and start the SuperSonic Sled demo with wine like you have done.

PS. Given that you keep these toolkit files in the same place, you need to run the export LD_LIBRARY_PATH line every time you close the shell or script or whatever you use to start it from. You can add the line to any startup script or whatever.

Easy right? hehe...

**Comment by Noobyuser** [comment]
WOW, thank You so much!!

I'm going to try this out over the weekend.

Thank You once more for taking the time to write this all down!
