### ISSUE TITLE
cudaImportExternalSemaphore: operation not supported

### ISSUE THREAD

**Issue by zhangwlgq** [SveSop/nvidia-libs#23]
Hi, I am using cudaImportExternalSemaphore in my program to import d3d12 resource, but it reports "operation not supported".
I think maybe it is due to cuda_runtime, how can I fix this?
Thank you.

**Comment by SveSop** [comment]
Do you have a executable minimal reproductive test i could run?

It might be somewhat tricky to work with d3d12 resources using vkd3d and set that up using wine i suppose, so a bit more info is needed before i can really answer that i am afraid.

**Comment by zhangwlgq** [comment]
> Do you have a executable minimal reproductive test i could run?
> 
> It might be somewhat tricky to work with d3d12 resources using vkd3d and set that up using wine i suppose, so a bit more info is needed before i can really answer that i am afraid.

Finally I gave up on doing this and instead found a workaround. Thank you anyway.
