### ISSUE TITLE
Error Building on Gentoo

### ISSUE THREAD

**Issue by LaNataliaaa** [SveSop/nvidia-libs#26]
I still can't figure out what the problem is, I've checked for the needed mingw libs , they are all compiled.

I'll attach the meson-build.log

`Build started at 2024-12-10T12:59:36.648645
Main binary: /usr/bin/python3.12
Build Options: -Dprefix=/home/natasha/nvidia-libs/test1/nvidia-libs-release -Dlibdir=x64 -Dbuildtype=release -Dstrip=True --cross-file=/home/natasha/nvidia-libs/wine-nvml/cross-mingw64.txt
Python system: Linux
The Meson build system
Version: 1.6.0
Source dir: /home/natasha/nvidia-libs/wine-nvml
Build dir: /home/natasha/nvidia-libs/test1/nvidia-libs-release/build.mingw64
Build type: cross build
Project name: wine-nvml
Project version: undefined
-----------
Detecting compiler via: `winegcc -b x86_64-w64-mingw32 --version` -> 0
stdout:
clang version 18.1.8
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm/18/bin
-----------
Running command: -x c -E -dM -
Sanity testing C compiler: winegcc -b x86_64-w64-mingw32
Is cross compiler: True.
Sanity check compiler command line: winegcc -b x86_64-w64-mingw32 sanitycheckc.c -o sanitycheckc_cross.exe -mno-cygwin -D_FILE_OFFSET_BITS=64 -c
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
C compiler for the host machine: winegcc -b x86_64-w64-mingw32 (clang 18.1.8 "clang version 18.1.8")
C linker for the host machine: winegcc -b x86_64-w64-mingw32 ld.lld 18.1.8
-----------
Detecting archiver via: `x86_64-w64-mingw32-ar --version` -> [Errno 2] No such file or directory: 'x86_64-w64-mingw32-ar'

meson.build:1:0: ERROR: Unknown linker(s): [['x86_64-w64-mingw32-ar']]
The following exception(s) were encountered:
Running `x86_64-w64-mingw32-ar --version` gave "[Errno 2] No such file or directory: 'x86_64-w64-mingw32-ar'"
`

**Comment by SveSop** [comment]
I honestly do not know. I have not used Gentoo in many years.

Maybe some path issue where meson cant really detect `x86_64-w64-mingw32-ar` at the expected path?
