### ISSUE TITLE
Actions build plus build issues 

### ISSUE THREAD

**Issue by AireagoirSteam** [SveSop/nvidia-libs#6]
Could an actions build be implemented so we can get the latest build of this.
Also I'm having issues building this on my machine.

Ubuntu Studio 20.04.5 lts with backports.

Here's the output as couldn't attach a file with the output.

./package-release.sh /home/aireagoir/Documents/nvidia-libs/build/
Submodule 'dxvk-nvapi' (https://github.com/SveSop/dxvk-nvapi.git) registered for path 'dxvk-nvapi'
Submodule 'wine-nvml' (https://github.com/SveSop/wine-nvml.git) registered for path 'wine-nvml'
Submodule 'wine-nvoptix' (https://github.com/SveSop/wine-nvoptix.git) registered for path 'wine-nvoptix'
Cloning into '/home/aireagoir/Documents/nvidia-libs/dxvk-nvapi'...
Cloning into '/home/aireagoir/Documents/nvidia-libs/wine-nvml'...
Cloning into '/home/aireagoir/Documents/nvidia-libs/wine-nvoptix'...
Submodule path 'dxvk-nvapi': checked out '691443b3fbf8d069b9c2388cb3f95f320cdcbbf2'
Submodule 'external/Vulkan-Headers' (https://github.com/KhronosGroup/Vulkan-Headers) registered for path 'dxvk-nvapi/external/Vulkan-Headers'
Cloning into '/home/aireagoir/Documents/nvidia-libs/dxvk-nvapi/external/Vulkan-Headers'...
Submodule path 'dxvk-nvapi/external/Vulkan-Headers': checked out '37164a5726f7e6113810f9557903a117498421cf'
Submodule path 'wine-nvml': checked out '25f6e57d96e10a2a9fb195b2103e9ebd254aa9df'
Submodule path 'wine-nvoptix': checked out '84d91e81b06fd4ad930e644e3d275032fce15708'
The Meson build system
Version: 0.53.2
Source dir: /home/aireagoir/Documents/nvidia-libs
Build dir: /home/aireagoir/Documents/nvidia-libs/build/nvidia-libs/build.64
Build type: cross build
Project name: nvidia-libs
Project version: v0.7
C compiler for the build machine: cc (gcc 9.4.0 "cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0")
C linker for the build machine: cc ld.bfd 2.34
C compiler for the host machine: winegcc (gcc 9.4.0 "gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0")
C linker for the host machine: winegcc ld.bfd 2.34
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Library dl found: YES
Program winebuild found: YES (/usr/bin/winebuild)
Program winegcc found: YES (/usr/bin/winegcc)
Program wrc found: YES (/usr/bin/wrc)
Run-time dependency threads found: YES
Build targets in project: 5

Found ninja-1.10.0 at /usr/bin/ninja
[4/8] Compiling C object 'dlls/nvcuda/ba00fc1@@nvcuda.dll@sha/internal.c.o'.
FAILED: dlls/nvcuda/ba00fc1@@nvcuda.dll@sha/internal.c.o 
winegcc -Idlls/nvcuda/ba00fc1@@nvcuda.dll@sha -Idlls/nvcuda -I../../../dlls/nvcuda -I../../.././include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O3 -fPIC -pthread -MD -MQ 'dlls/nvcuda/ba00fc1@@nvcuda.dll@sha/internal.c.o' -MF 'dlls/nvcuda/ba00fc1@@nvcuda.dll@sha/internal.c.o.d' -o 'dlls/nvcuda/ba00fc1@@nvcuda.dll@sha/internal.c.o' -c ../../../dlls/nvcuda/internal.c
../../../dlls/nvcuda/internal.c:26:10: fatal error: windef.h: No such file or directory
   26 | #include "windef.h"
      |          ^~~~~~~~~~
compilation terminated.
winegcc: /usr/bin/gcc failed
[5/8] Compiling C object 'dlls/nvcuda/ba00fc1@@nvcuda.dll@sha/nvcuda.c.o'.
FAILED: dlls/nvcuda/ba00fc1@@nvcuda.dll@sha/nvcuda.c.o 
winegcc -Idlls/nvcuda/ba00fc1@@nvcuda.dll@sha -Idlls/nvcuda -I../../../dlls/nvcuda -I../../.././include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O3 -fPIC -pthread -MD -MQ 'dlls/nvcuda/ba00fc1@@nvcuda.dll@sha/nvcuda.c.o' -MF 'dlls/nvcuda/ba00fc1@@nvcuda.dll@sha/nvcuda.c.o.d' -o 'dlls/nvcuda/ba00fc1@@nvcuda.dll@sha/nvcuda.c.o' -c ../../../dlls/nvcuda/nvcuda.c
../../../dlls/nvcuda/nvcuda.c:30:10: fatal error: windef.h: No such file or directory
   30 | #include "windef.h"
      |          ^~~~~~~~~~
compilation terminated.
winegcc: /usr/bin/gcc failed
[6/8] Generating version with a custom command.
ninja: build stopped: subcommand failed

**Comment by SveSop** [comment]
What is your system version of wine (wine-dev or wine-staging-dev)?

I have considered setting up actions for this, so maybe some time if i get around to it.
Ill try make pre-built releases a bit more often tho 😄

**Comment by SveSop** [comment]
In the meantime - i posted a new release with binaries now.
[v0.7.7](https://github.com/SveSop/nvidia-libs/releases/tag/v0.7.7)

**Comment by AireagoirSteam** [comment]
Thanks and should be wine staging dev ill try it again and see if it builds. Also not sure if my cuda is setup properly since my own wine staging doesn't have the nvcuda library which I could have sworn it did.

Yet i have cuda set up which gives me a version number any ideas.

Also thank for the new version release

**Comment by SveSop** [comment]
Not sure if you actually need staging, but you need version >=8.0. I just have not tested to build with regular wine-dev as i always use wine-staging-dev when i build.

NVAPI has been disabled in recent wine-staging ref [Staging commit](https://github.com/wine-staging/wine-staging/commit/6c3797b3e8dba19698328c411dd2082b2c45b849)

The reported cuda version that nvcuda does comes from your driver. If the driver supports cuda 12, the nvcuda implementation will report this (even tho not all cuda functions are supported). Sorry if i misinterpreted what you were asking.

**Comment by AireagoirSteam** [comment]
No ypu handt misinterpret. Dint know they disabled nvcuda.l which kinda sucks.

Oddly I've used wine ge on lutris and heroic and tried the physx demo using geek3d and gpu physx is disabled.

I'll try the updated binaries in a normal prefix and I'll try the batman physx demo see if that uses the gpu.

Wished I'd known about your this report sooner since my laptop would have benefited.

**Comment by SveSop** [comment]
PhysX needs separate install - ie. `winetricks physx`

**Comment by SveSop** [comment]
Closing as there has been no further comments on this.
