### ISSUE TITLE
nvidia-libs fails to install on wine-8.9 when configured with the "new WoW64 approach" 

### ISSUE THREAD

**Issue by schloegl** [SveSop/nvidia-libs#7]
nvidia-libs fails to install on wine-8.9 when configured with the "new WoW64 approach" (i.e. configure --enable-archs=i386,x86_64 ...") with this error:

`
meson.build:5:38: ERROR: C shared or static library 'dl' not found `

The full meson-log.txt file is attached. This is problem does not occur when trying to install nvidia-libs on wine-8.9 with the old "shared Wow64" [1] configuration.

[1] https://wiki.winehq.org/Building_Wine#Shared_WoW64

[meson-log.txt](https://github.com/SveSop/nvcuda/files/11708334/meson-log.txt)

**Comment by SveSop** [comment]
Not really sure i understand what this "new WoW64 approach" really means?
I dont have a chance to test all available compilers/distro's/customization/insert-whatever-you-like to compile this without issues. I compile using ArchLinux and that works without issues. I have also tested compiling under Ubuntu 22.04, and it compiles, but throw warnings `has virtual functions and accessible non-virtual destructor [-Wnon-virtual-dtor]`. This is just a warning and the binaries seemingly works fine.

Both compiles i just tested - Arch and Ubuntu have wine-staging-8.9 installed. 

Debian using gcc 10.2 could be an issue perhaps, and it could be some package missing for you (eg. glibc-devel or similar). Are you using WineHQ provided wine package as described here: [https://wiki.winehq.org/Debian](https://wiki.winehq.org/Debian) ?
I do not believe you need staging, but i have not tried to compile the package with wine-devel. Your logfiles seem to indicate `8.9-ea`, but i do not know what that means? Custom wine version of sorts?

**Comment by schloegl** [comment]
Ok, I'm trying to clarify here: 
- I'm not using wine-staging. Since gpu support is not included anymore, I do not see any benefit it using wine-staging. 

- I'm compiling wine from source on debian11 here. I'm testing two approaches. 
a) the old "shared Wow64" approach as described in [1]. This is the 

```
cd $WD/wine-build64 && $WD/wine-$VER/configure --enable-win64  --prefix=$PREFIX && \
   make -j4 && make install && 
cd $WD/wine-build32 && $WD/wine-$VER/configure --prefix=$PREFIX --with-wine64=$WD/wine-build64 && \
   make -j4 && make install

```

b) the second approach is the new "wow64" approach (-ea refers to --enable-archs= ") as described in [2]. This 

`
$WD/wine-$VER/configure --enable-archs=i386,x86_64 --prefix=$PREFIX-ea 
`

I assume option a) is still the default and used for the precompiled binaries. I can confirm that nvidia-libs works with option a) without the need for wine-staging. 

nvidia-libs fails to compile when wine is compiled with option b). 


[1] https://wiki.winehq.org/Building_Wine#Shared_WoW64
[2] https://www.winehq.org/announce/8.0

**Comment by SveSop** [comment]
Requirements for self-compiling nvidia-libs is WineHQ provided binaries. Other custom/self-compiled/proton/wine-GE versions of wine, is up to the user to solve.

Closing this issue as a "wontfix".

**Comment by SveSop** [comment]
And as a possible sidenote - The very reason libs like nvapi/nvcuda++ was discontinued from the staging tree altogether was most likely this issue in the first place.

**Comment by SveSop** [comment]
Had forgotten about this quite a while now, but i have done testing with wine compiled as wow64 (not compiling the library itself, but using nvcuda).

The 64-bit library works as it should, but 32-bit will not. To get this done "properly" it requires a huge rework of the library, and afaik 32-bit nvcuda is not really being used for anything but VERY old stuff. I know only of a couple of things that would require 32-bit libraries and none of the samples from nvidia's github can be compiled as 32-bit anymore using visual studio. They can possibly be compiled for linux, but that is of no use.

So, there would be 2 options:
1. Just leave it as is, and possibly just make a update to the installscript so it only installs 64-bit when wow64 mode is used
2. Put in a huge and lengthy effort to convert this to the "new" method of using windows/unix libs for wine (should probably be done.. fear all the work tbh), and compile a 32-bit library that cannot really be tested or verified in any way (even more conversion work for all pointers/long long int's and so on).

I do not really feel up to doing the last....

**Comment by WinterSnowfall** [comment]
@SveSop I'm sure you're probably aware of this by now, but Arch has started packaging Wine in WoW64 mode ever since 10.8-2, and as such you can no longer build nvidia-libs (or nvcuda, really) on Arch. I've reverted to a pre-WoW64 Wine package version for now and that works as expected.

In case anyone is curious, the most recent package that's still usable for nvidia-libs builds is: `pacman -U https://archive.archlinux.org/packages/w/wine/wine-10.8-1-x86_64.pkg.tar.zst`

I though it worth mentioning (again) because the situation is only going to get worse over time, I imagine 😅.

**Comment by SveSop** [comment]
Well... The package will work in 64-bit mode, even if it wont build if you are using arch. I'll look into adding some build flag i guess... `--no32` or someshit, so that the nvcuda/nvenc packages wont be built. nvapi will still build, as this should not rely on any particular 32-bit package afaik.

Unless NVIDIA decides to release a complete full opensource version of nvcuda, the chances of building the 32-bit nvcuda lib as "wow64" = zero. There is way too many unknown structs hidden behind opaque void's in many many undocumented internal routines (we are talking about hundreds). That will not happen.

I am aware that this is a separate issue, just wanted to make clear that there will NOT ever be a 32-bit "wow64" version of nvcuda.

But will see if i can modify the buildscript so that one can build only the 64-bit libs using arch.

**Comment by WinterSnowfall** [comment]
> I am aware that this is a separate issue, just wanted to make clear that there will NOT ever be a 32-bit "wow64" version of nvcuda.

Sad to hear that, but it is what it is.

> But will see if i can modify the buildscript so that one can build only the 64-bit libs using arch.

If possible, it would be nice to simply skip compilation of the 32-bit lib should 'dl' not be detected properly. That would mean you could still compile 32-bit with older Wine versions in Arch, and new ones will work too, but compile just 64-bit. Best of both worlds.

**Comment by SveSop** [comment]
Could you try the updated buildscript here: https://github.com/SveSop/nvidia-libs/tree/script

Hopefully the installscript should also detect that nvcuda/enc dlls is not there and not add empty symlinks.

Build using `./package-release.sh somename /home/someuser --no32`

I tested building this using docker, and it did seem to work with a "slim" arch docker, so hopefully it will be useful. Let me know 👍

**Comment by schloegl** [comment]
This looks good to me, I was able to run CUDA-Z and it recognized the GPU's. Finally, this issue seems to be solved.
