### ISSUE TITLE
nvidia-libs is compatible with driver 470 ?

### ISSUE THREAD

**Issue by Augusto7743** [SveSop/nvidia-libs#9]
Hello.
The nvidia-libs current version can run if in host OS is using Geforce 600 with driver 470 ?
If not what is the last version with support for driver 470 ?

Have an nice week.

**Comment by SveSop** [comment]
It seems from my history of README.md it is v0.7.3 
I updated the "requirement" for v0.7.4, but i do not know what would fail, other than maybe new CUDA calls or OptiX calls that would not be supported...

It is somewhat of a "soft" requirement, but it CAN fail if the driver does not support certain CUDA calls i would say.

**Comment by Augusto7743** [comment]
Thanks for reply.
nvidia-libs 0.7.6 is the last version compatible for Geforce 600 and some GT 700 series Kepler using driver 470.
I suggest to add that information in https://github.com/SveSop/nvidia-libs helping others users.
Have an nice day.

**Comment by SveSop** [comment]
> Thanks for reply. nvidia-libs 0.7.6 is the last version compatible for Geforce 600 and some GT 700 series Kepler using driver 470. I suggest to add that information in https://github.com/SveSop/nvidia-libs helping others users. Have an nice day.

Any chance you could elaborate on exactly how this was tested? Any wine logs `WINEDEBUG=-all,+nvcuda` or something similar?

**Comment by Augusto7743** [comment]
Only tested with CUDA-Z ....
I am an "novice" WINE user ....
What command to do for creating logs when testing and upload to you ?

**Comment by SveSop** [comment]
Interesting logs for me when it comes to CUDA-Z would be to run it like this:
`WINEDEBUG=-all,+nvcuda wine ./CUDA-Z-0.10.251-64bit.exe > CudaZ.log 2>&1`

Then you can upload the `cuda.log` file

**Comment by Augusto7743** [comment]
Here the log
WINE Staging 8.10 with dxvk and nvidia-libs 0.7.6
Host using proprietary driver 470
[CudaZ.log](https://github.com/SveSop/nvidia-libs/files/11776356/CudaZ.log)

**Comment by SveSop** [comment]
What happens if you run nvidia-libs v0.7.10?

**Comment by Augusto7743** [comment]
CUDA-Z report "Not CUDA device"
Here the video card is GT 640 Kepler.

**Comment by SveSop** [comment]
> CUDA-Z report "Not CUDA device" Here the video card is GT 640 Kepler.

Well, that message is as helpful to me as someone walking into a car dealership saying "Hey, something is wrong with my car! Fix it!" and then stomp off without even letting them pop to hood....

Please create a log in the same manner as you did here https://github.com/SveSop/nvidia-libs/issues/9#issuecomment-1595365662

**Comment by Augusto7743** [comment]
nvidia libs version 0.7.10
CUDA-Z show an message "Not CUDA device" and close. running the command
WINEDEBUG=-all,+nvcuda wine ./CUDA-Z-0.10.251-64bit.exe > CudaZ.log 2>&1

The log is 0 bytes.

However GPU_Caps_Viewer_1.60.0.0 start and done an log.

If is installed nvidia libs version 0.7.6 not is possible start GPU_Caps_Viewer_1.60.0.0 happening crash closing it.

GPU_Caps_Viewer with 2 logs.
If you need any test or other command line reply me.

[GPU_Caps_Viewer.zip](https://github.com/SveSop/nvidia-libs/files/11798046/GPU_Caps_Viewer.zip)
